import { createSlice, configureStore } from "@reduxjs/toolkit";

// Import necessary dependencies

// Create a slice of the Redux state for authentication
const authSlice = createSlice({
    name: "auth", // Name of the slice
    initialState: { user: "", isLoggedIn: false }, // Initial state of the slice
    reducers: {
        // Reducer function to set the login status to true
        login(state) {
            state.isLoggedIn = true; // Set isLoggedIn to true when the user logs in
        },
        // Reducer function to set the login status to false
        logout(state) {
            state.isLoggedIn = false
            
            ; // Set isLoggedIn to false when the user logs out
        },
    },
});

// Export action creators generated by the authSlice
export const authActions = authSlice.actions;

// Create a Redux store with the authSlice reducer
export const store = configureStore({
    reducer: authSlice.reducer, // Configure the store with the authSlice reducer
});
